app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/',  
            array('as' => 'eecfin.home', 
                    'uses' => 'HomeController@home'));

Route::get('/eecfin', function()
{
    return View::make('hello');
});


Route::get('/home', 
            array('as' => 'eecfin.home', 
                    'uses' => 'HomeController@home'));

Route::get('/about', 
            array('as' => 'eecfin.about', 
                    'uses' => 'PagesController@about'));

Route::get('/media', 
            array('as' => 'eecfin.media', 
                    'uses' => 'PagesController@media'));

Route::get('/live', 
            array('as' => 'eecfin.live', 
                    'uses' => 'PagesController@live'));

Route::get('/conference/{title}', 
            array('as' => 'eecfin.conference', 
                    'uses' => 'PagesController@conference'));

Route::get('/conference/{title}/{day}', 
            array('as' => 'eecfin.conference.day', 
                    'uses' => 'PagesController@conferenceDay'));

Route::get('/conference/{title}/{day}/{video}', 
            array('as' => 'eecfin.conference.day.video', 
                    'uses' => 'PagesController@conferenceDayVideo'));

Route::get('/conference', 
            array('as' => 'eecfin.conference.index', 
                    'uses' => 'PagesController@conference'));

// Route::get('/members', 
//             array('as' => 'eecfin.members.index', 
//                     'uses' => 'MembersController@index'));

Route::get('/member', function() {   
    return File::get(public_path().'/members/index.html');
});

Route::get('/api/members', 
            array('as' => 'eecfin.api.members', 
                    'uses' => 'Controllers\Api\MembersController@index'));

Route::group(array('before' => 'auth', 'prefix' => 'super'), function(){

    Route::resource('sermons','SermonsController');
    
});

app/models/Sermon.php
<?php

use LaravelBook\Ardent\Ardent;

class Sermon extends Ardent {

    protected $table = 'sermons';

    protected $guarded = array();

    public static $rules = array(
    );

    public function user()
    {
        return $this->belongsTo('User');
    }

}

app/controllers/SermonsController.php
<?php

class SermonsController extends BaseController {

    protected $layout = 'layouts.master';
    
    public function index()
    {
        $this->layout->content = View::make('about');
    }

    public function create()
    {
        $users = User::all();
        $this->layout->content = View::make('sermons.create')->with(compact("users"));

    }

    public function store(){
        Sermon::create(Input::except('q'));
        Redirect::back();
    }

    public function edit(){
        return Sermon::orderBy('delivered_at', 'desc')->get();
    }

    public function update(){
        return Sermon::orderBy('delivered_at', 'desc')->get();
    }

}

app/views/sermons/create.blade.php
{{ Form::open(array('route' => 'super.sermons.store', 'method' => 'post', 'class' => 'form-horizontal')) }}
    <div class="inner">
        <fieldset>
            <legend>Add sermon</legend>
            <div class="control-group">
                <label class="control-label" for="code">Preacher</label>
                <div class="controls">
                    <select name="user_id" id="">
                        @foreach($users as $user)
                            <option value="{{ $user->id }}"> {{ $user->first_name }} {{ $user->last_name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="title">Title</label>
                <div class="controls">
                    <input class="input-large" name="title" id="name" type="text" value="{{ Input::old('title') }}">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="subtitle">Sub title </label>
                <div class="controls">
                    <input class="input-large" name="subtitle" id="subtitle" type="text" value="{{ Input::old('subtitle') }}">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="image">Image file</label>
                <div class="controls">
                    <input class="input-large" name="image" id="image" type="text" value="{{ Input::old('image') }}" placeholder="eg. cross.jpg">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="audio">Audio file</label>
                <div class="controls">
                    <input class="input-large" name="audio" id="audio" type="text" value="{{ Input::old('audio') }}" placeholder="eg. 26_01_14_muluwork.mp3">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="delivered_at">Delivered at</label>
                <div class="controls">
                    <input class="input-large" name="delivered_at" id="delivered_at" type="text" value="{{ Input::old('delivered_at') }}" placeholder="eg. 2014-01-26 13:15:38">
                </div>
            </div>
        </fieldset>
        
    </div>
    <div class="form-actions">
        <a href="{{ route('super.sermons.index') }}" class="btn btn-warning  btn-large">Takaisin</a> 
        <button type="submit" class="btn btn-success btn-large">Tallenna</button>
    </div>
{{ Form::close() }}